### ISSUE TITLE
ffprobe and ffmpeg paths are not getting read from flavy config

### ISSUE THREAD

**Issue by voodoo2345** [Folour/Flavy#2]
![flavy_flour_error](https://cloud.githubusercontent.com/assets/13540406/17712044/e77cbc18-6411-11e6-8585-999849e25398.png)

I had to change Base class of this library to remove this error, although a bad approach as library's paths are now static. I am running short on deadline.

**Comment by Folour** [comment]
Fixed in version 1.0.1
