### ISSUE TITLE
Support missing for Laravel 5.3

### ISSUE THREAD

**Issue by nitishrajuprety** [folour/flavy#3]
I recently tried adding this package in Laravel 5.3 project but it won't install on above 5.2. I hope support for 5.3 is coming soon. In the meantime, can someone help me on how to install the package manually.

**Comment by shealan** [comment]
+1

**Comment by Folour** [comment]
I will testing this package on laravel 5.3. Thanks for feedback, and sorry for delay.

**Comment by reinierkors** [comment]
Package works on 5.3.

To use it now:
https://github.com/reinierkors/Flavy
```
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/reinierkors/Flavy"
        }
    ],
```
and add `"reinierkors/flavy": "dev-master"` to your composer.json. 

Then just follow the install instructions.
